### ISSUE TITLE
remove get_magic_quotes_gpc() related code

### ISSUE THREAD

**Issue by nbuy** [xoopscube/xcl#121]
~~~
DEPRECATED: Function get_magic_quotes_gpc() is deprecated
~~~
It will be remove and cleanups.

fix will be
- get_magic_quotes_gpc() assume return false
- cleanup and remove around code
- warning for backward compatible

**Comment by gigamaster** [comment]
I merge this to branch Develop. 
XCL 2.3 minimum requirement PHP 7.x.x

**Comment by nbuy** [comment]
Thanks!
