### ISSUE TITLE
Mixed Tables engine MyISAM ad InnoDB

### ISSUE THREAD

**Issue by gigamaster** [xoopscube/xcl#194]
TODO : change modules (user, message, etc) mysql.sql tables to engine InnoDB

**Comment by nbuy** [comment]
Now ignore "ENGINE=MyISAM" in mysql.sql definisions.
[code sqlutility.php at L157](https://github.com/xoopscube/xcl/blob/32504f152604ef71edd317cc394ac3c55f2fbefc/html/class/database/sqlutility.php#L157)
You will be add code here if forced "ENGINE=InnoDB".
Or assign to me? ^^;

**Comment by gigamaster** [comment]
I have changed sql of modules to Engine InnoDB and I was surprise to find out that sqlutility was forcing utf8. The MySQL's database was set with “utf8mb4” (means “UTF-8”) but maybe legacy code has other utf8 code ref.  and I cannot tell if japanese really needs "utf8mb4".

**Comment by nbuy** [comment]
You are collect using "utf8mb4".
I don't know that option right now.
It looks "utf8" was just trap. 😅
(Can't support like this comment. 😉)

**Comment by gigamaster** [comment]
The test was ok from PHP71 to 74, MySQL5.6 to v8. Now, I am fixing default themes and legacy templates (firefox) and will push (InnoDB, bugfix and warnings) in a few hours.
