### ISSUE TITLE
Templates missing

### ISSUE THREAD

**Issue by mambax7** [xoopscube/xcl#233]
Installation went fine, but after switching to the main screen, I've got that:
```
Warning [Xoops]: Smarty error: unable to read resource: "xcl_default/component/app_meta.html" in file C:\wamp64\www\xcl\xoops_trust_path\libs\smarty\Smarty.class.php line 1108 (1)
Warning [Xoops]: Smarty error: unable to read resource: "xcl_default/component/layout_full.html" in file C:\wamp64\www\xcl\xoops_trust_path\libs\smarty\Smarty.class.php line 1108 (1)
Warning [Xoops]: Smarty error: unable to read resource: "xcl_default/component/app_footer.html" in file C:\wamp64\www\xcl\xoops_trust_path\libs\smarty\Smarty.class.php line 1108 (1)
```

After I tried to refresh, I've got:

`Protector detects site manipulation.`

PHP 7.4.8

**Comment by gigamaster** [comment]
Oops... I've changed default theme design to implement xclayout helper (visually create flex layout) and the new components are "Unversioned files". PHPStorm makes it pretty clear, guess I mess up ^_^' 

> 
> 
> Installation went fine, but after switching to the main screen, I've got that:
> 
> ```
> Warning [Xoops]: Smarty error: unable to read resource: "xcl_default/component/app_meta.html" in file C:\wamp64\www\xcl\xoops_trust_path\libs\smarty\Smarty.class.php line 1108 (1)
> Warning [Xoops]: Smarty error: unable to read resource: "xcl_default/component/layout_full.html" in file C:\wamp64\www\xcl\xoops_trust_path\libs\smarty\Smarty.class.php line 1108 (1)
> Warning [Xoops]: Smarty error: unable to read resource: "xcl_default/component/app_footer.html" in file C:\wamp64\www\xcl\xoops_trust_path\libs\smarty\Smarty.class.php line 1108 (1)
> ```
> 
> After I tried to refresh, I've got:
> 
> `Protector detects site manipulation.`
> 
> PHP 7.4.8

Oops ... I've changed the default theme design and created a new theme xcl-base to implement xclayout helper (visually create flex layout components). I've found the new theme and components under "Unversioned files", PHPStorm makes it pretty clear, but I forgot to merge up ^ _ ^ '
Thanks, I'm fixing this and some other UI issues. Cheers ^_^/

**`Protector detects site manipulation.`** 
This happens as an alert whenever a change is detected in the default install, (other links still work).   
Login to admin and update the module protector.

**Comment by mambax7** [comment]
Are the changes now merged?
